Update localization.ru.lua
DeadlyBossMods/DBM-Retail pull request #770
Opened 2022-06-16 20:40 UTC by Hollicsh

Add phrases. Translation later.

2022-06-16 20:42 UTC, MysticalOS requested changes
no reason to add placeholders, i'll leave this open for now but overwriting english ones with english ones isn't needed. You'll want the actual RU text or better to leave blank or commented out for now.

2022-06-18 17:28 UTC, Molkree commented
Wowhead has these phrases.
[Xy'noc](https://ru.wowhead.com/npc=176758)
Докучают разъяренные звери? У нас есть решение!
[Venza Goldfuse](https://ru.wowhead.com/npc=176705)
Вот мой шанс! Топор будет моим!
[Al'dalil](https://ru.wowhead.com/npc=178074)
Прости нас за вторжение, Со'лея. Кажется, сейчас не самое подходящее время.

2022-06-18 19:58 UTC, Hollicsh commented
Yeah. Done.

2022-06-18 20:05 UTC, Molkree requested changes
You've added SPACEs before TABs accidentally.

2022-06-18 20:05 UTC, Molkree commented on DBM-Party-Shadowlands/localization.ru.lua
> + 	VenzaRPTrigger		= "Вот мой шанс! Топор будет моим!"
```suggestion
	AchilliteRPTrigger	= "Докучают разъяренные звери? У нас есть решение!",
	VenzaRPTrigger		= "Вот мой шанс! Топор будет моим!"
```

2022-06-18 20:05 UTC, Molkree commented on DBM-Party-Shadowlands/localization.ru.lua
> + 	RPTrigger	= "Прости нас за вторжение, Со'лея. Кажется, сейчас не самое подходящее время."
```suggestion
	RPTrigger	= "Прости нас за вторжение, Со'лея. Кажется, сейчас не самое подходящее время."
```

2022-06-18 20:10 UTC, MysticalOS commented
I also want to add that wowhead quotes are not same as in game verified ones either. Sometimes those are typed up by users and not copy/pasted so they can have missing spaces or punctuation. Since these are actual trigger strings they need to be verified from game or they might note even work.

2022-06-18 20:25 UTC, Hollicsh commented
Let's leave it like this for now.

2022-06-21 09:18 UTC, Hollicsh commented
I checked all the phrases in the game, they match 100%.

2022-07-02 15:29 UTC, MysticalOS approved these changes

2022-07-02 15:30 UTC, merged